[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"


# resolve the "new" URL to a function
[[redirects]]
  from = "/new"
  to = "/.netlify/functions/newLolly"
  status = 200


# unfound lollies should look to the API directly
# [[redirects]]
  # from = "/lolly/*"
  # to = "/lolly/fetch?id=:splat"
  # force = false # Only apply this rule if no file is founds


[[redirects]]
  from = "/lolly/*"
  to = "/.netlify/functions/showLolly?id=:splat"
  # status = 200
  # sforce = false # Only apply this rule if no file is founds




# Not even available via the API? THis really id a 404
[[redirects]]
  from = "*"
  to = "/melted/index.html"
  status = 404

