[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"



# unfound lollies should look to the API directly
[[redirects]]
  from = "/lolly/new"
  to = "/.netlify/functions/newLolly"
  status = 200


#truley infound lollies need a real 404
[[redirects]]
  from = "/lolly/melted"
  to = "/melted/index.html"
  status = 404


# unfound lollies should look to the API directly
[[redirects]]
  from = "/lolly/*"
  to = "/.netlify/functions/getLolly?id=:splat"
  status = 404
