[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"


# resolve the "new" URL to a function
[[redirects]]
  from = "/new"
  to = "/.netlify/functions/newLolly"
  status = 200


# unfound lollies should look to the API directly
# [[redirects]]
#   from = "/lolly/*"
#   to = "/lolly/fetch?id=:splat"

