[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"


# resolve the "new" URL to a function
[[redirects]]
  from = "/new"
  to = "/.netlify/functions/newLolly"
  status = 200

# unfound lollies should proxy to the API directly
[[redirects]]
  from = "/lolly/*"
  to = "/.netlify/functions/showLolly?id=:splat"
  status = 302

# Not even available via the API? This really is a 404
[[redirects]]
  from = "/*"
  to = "/melted/index.html"
  force = false
  status = 404


# Use a Netlify Build plugin to enable incremental builds
[[plugins]]
  package = "./plugins/track-latest"

