[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"


[[redirects]]
  from = "/*"
  to = "/us/:splat"
  conditions = {Country = ["GB"]}


[[redirects]]
  from = "/us/:locale/css/:file"
  to = "/css/:file"

[[redirects]]
  from = "/us/:locale/js/:file"
  to = "/js/:file"



# resolve the "new" URL to a function
[[redirects]]
  from = "/new"
  to = "/.netlify/functions/newLolly"
  status = 200

# unfound lollies should proxy to the API directly
[[redirects]]
  from = "/lolly/*"
  to = "/.netlify/functions/showLolly?id=:splat"
  status = 302

[[redirects]]
  from = "/popsicle/*"
  to = "/.netlify/functions/showLolly?id=:splat"
  status = 302



# Not even available via the API? This really is a 404
[[redirects]]
  from = "/*"
  to = "/melted/index.html"
  force = false
  status = 404




# Use a Netlify Build plugin to enable incremental builds
[[plugins]]
  package = "./plugins/track-latest"

